### PR TITLE
Update tool to python3 and fix requirement differences, update REAME

### LINKED ISSUE #254: Fix requirement install with pip's new dependency conflict resolving
When running pip install -r requirements.txt , got this
```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

spdx-license-matcher 0.0.1 requires jpype1==0.6.3, but you'll have jpype1 1.0.1 which is incompatible.
spdx-license-matcher 0.0.1 requires python-dotenv==0.13.0, but you'll have python-dotenv 0.14.0 which is incompatible.
spdx-license-matcher 0.0.1 requires requests==2.22.0, but you'll have requests 2.24.0 which is incompatible.```
```

When running `pip install -r requirements.txt --use-feature=2020-resolver`, it shows
```
ERROR: Cannot install requests==2.24, django-oauth-toolkit 1.3.2 and -r requirements.txt (line 16) because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested requests==2.24
    django-oauth-toolkit 1.3.2 depends on requests>=2.13.0
    spdx-license-matcher 0.0.1 depends on requests==2.22.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

### PR DESCRIPTION
**Pull request by rtgdk**
- Updated requirements.txt to fix https://github.com/spdx/spdx-online-tools/issues/254 with rtgdk_python3 branch for https://github.com/spdx/spdx-online-tools/pull/205

- Ran 2to3 tool over the directory to convert python2 to python3 codes, minimal changes with dictionary.keys()/items() functions

- Updated README to include download and launch redis  #11 

- `failobj` is not present as argument in python3 (I worked with py3.9), changed it to default

- Updated imports to use `<parent>.<file>` format to fix `ModuleNotFoundError: No module named 'normalize'` as relative import works in a different way in python3

### CODE REVIEW

**Comment by rtgdk** [comment]
@Ugtan @goneall Please review.
Also, @Ugtan please check out https://github.com/spdx/spdx-license-matcher/issues/11 issue.

**Review by Ugtan — APPROVED** [review]
Looks good to me, LGTM. @rtgdk

**Comment by rtgdk** [comment]
@Ugtan @goneall Please merge this. We need to create a new release (v2.0) with this commit to import in spdx-online-tool python3 branch. Also, jpype>=1.0.x doesn't work with python2. So this release build will only work for python3 going forward. I think this is expected and fine since we are upgrading the whole codebase around it to python3.
Also, please provide me write access for this repo.

**Comment by Ugtan** [comment]
@rtgdk Merged the branch. Also, check your mail you should get a invite for collaboration.

**Pull request merged**
